# Beta values
FOG_DENSITY_SMALL_BETA = 0.0025
FOG_DENSITY_MEDIUM_BETA = 0.005
FOG_DENSITY_HIGH_BETA = 0.01

BETAS = [FOG_DENSITY_SMALL_BETA, FOG_DENSITY_MEDIUM_BETA, FOG_DENSITY_HIGH_BETA]
BETAS_STR = ["SMALL", "MEDIUM", "HIGH"]

# RGB image must be smaller or equal to sift/flow images
RGB_IMG_WIDTH = 200
RGB_IMG_HEIGHT = 120

SIFT_FLOW_IMG_WIDTH = 400
SIFT_FLOW_IMG_HEIGHT = 240